export const AppIcons = {
  // category: 'sell',
  // product: 'lunch_dining',
  // addon: 'extension',
  // order: 'shopping_cart',
  // locked: 'lock',
  // unlocked: 'lock_open',
  // error: 'error',
  // dashboard: 'dashboard',
  // stocks: 'inventory',
  // user: 'person',
  // users: 'people',
  // add_user: 'person_add',
  // settings: 'settings',
  // logout: 'logout',
  // home: 'home',
  // invoice_history: 'history',
  // reports: 'assessment',
  // cashier: 'attach_money',
  // login: 'login',
  // inventory: 'inventory',
  // success: 'check_circle',
  // visible: 'visibility',
  // invisible: 'visibility_off',
  // generate_password: 'password',
  // copy: 'content_copy',
  // info: 'info',
  // edit: 'edit',
  // delete: 'delete',
  // add: 'add',
  // login_audit: 'history',
  // more_menu: 'more_vert',
  // good: 'thumb_up',
  login: 'login',
  logout: 'logout',
  home: 'home',
  error: 'error',
  info: 'info',
  edit: 'edit',
  delete: 'delete',
  add: 'add',
  settings: 'settings',
  menu: 'menu',
  table: 'table_view',
  location: 'location_on',
  user: 'person',
  users: 'people',
  staff: 'people_alt',
  add_user: 'person_add',
  promos: 'local_offer',
  invoice_history: 'history',
  reports: 'assessment',
  food_menu: 'menu_book',
  meal: 'lunch_dining',
  close: 'close',
  phone: 'phone',
};

export type AppIconName = keyof typeof AppIcons;
